### ISSUE TITLE
skutil.h2o.H2OOversamplingClassBalancer Runtime Error 

### ISSUE THREAD

**Issue by mbokshi1** [tgsmith61591/skutil#38]
Getting a runtime error while trying to return the H2O frame after H2OOversamplingClassBalancer.

Python 2.7.11 :: Anaconda 2.3.0 (64-bit)
H2O version:     3.10.0.7

Note - error is too long to include in the message box, so trimming it down by cutting most of the middle of the error trace.

Error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    688                 type_pprinters=self.type_printers,
    689                 deferred_pprinters=self.deferred_printers)
--> 690             printer.pretty(obj)
    691             printer.flush()
    692             return stream.getvalue()

/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    407                             if callable(meth):
    408                                 return meth(obj, self, cycle)
--> 409             return _default_pprint(obj, self, cycle)
    410         finally:
    411             self.end_group()

/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
    527     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    528         # A user-provided repr. Find newlines and replace them with p.break_()
--> 529         _repr_pprint(obj, p, cycle)
    530         return
    531     p.begin_group(1, '<')

/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
    709     """A pprint that just redirects to the normal repr function."""
    710     # Find newlines and replace them with p.break_()
--> 711     output = repr(obj)
    712     for idx,output_line in enumerate(output.splitlines()):
    713         if idx:

/home/eobg/.local/lib/python2.7/site-packages/h2o/frame.pyc in __repr__(self)
    318             stk = traceback.extract_stack()
    319             if not ("IPython" in stk[-2][0] and "info" == stk[-2][2]):
--> 320                 self.show()
    321         return ""
    322 

/home/eobg/.local/lib/python2.7/site-packages/h2o/frame.pyc in show(self, use_pandas)
    330             print("This H2OFrame has been removed.")
    331             return
--> 332         if not self._ex._cache.is_valid(): self._frame()._ex._cache.fill()
    333         if H2ODisplay._in_ipy():
    334             import IPython.display

/home/eobg/.local/lib/python2.7/site-packages/h2o/frame.pyc in _frame(self, fill_cache)
    375 
    376     def _frame(self, fill_cache=False):
--> 377         self._ex._eager_frame()
    378         if fill_cache:
    379             self._ex._cache.fill()

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _eager_frame(self)
     83         if not self._cache.is_empty(): return self
     84         if self._cache._id is not None: return self  # Data already computed under ID, but not cached locally
---> 85         return self._eval_driver(True)
     86 
     87     def _eager_scalar(self):  # returns a scalar (or a list of scalars)

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _eval_driver(self, top)
     96 
     97     def _eval_driver(self, top):
---> 98         exec_str = self._do_it(top)
     99         res = ExprNode.rapids(exec_str)
    100         if 'scalar' in res:

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _do_it(self, top)
    123         if self._cache._id is not None: return self._cache._id  # Data already computed under ID, but not cached
    124         # assert isinstance(self._children,tuple)
--> 125         exec_str = "({} {})".format(self._op, " ".join([ExprNode._arg_to_expr(ast) for ast in self._children]))
    126         gc_ref_cnt = len(gc.get_referrers(self))
    127         if top or gc_ref_cnt >= ExprNode.MAGIC_REF_COUNT:

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _arg_to_expr(arg)
    136             return "[]"  # empty list
    137         elif isinstance(arg, ExprNode):
--> 138             return arg._do_it(False)
    139         elif isinstance(arg, ASTId):
    140             return str(arg)

...............................................................................................................................

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _do_it(self, top)
    123         if self._cache._id is not None: return self._cache._id  # Data already computed under ID, but not cached
    124         # assert isinstance(self._children,tuple)
--> 125         exec_str = "({} {})".format(self._op, " ".join([ExprNode._arg_to_expr(ast) for ast in self._children]))
    126         gc_ref_cnt = len(gc.get_referrers(self))
    127         if top or gc_ref_cnt >= ExprNode.MAGIC_REF_COUNT:

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _arg_to_expr(arg)
    132     @staticmethod
    133     def _arg_to_expr(arg):
--> 134         if arg is not None and isinstance(arg, range): arg = list(arg)
    135         if arg is None:
    136             return "[]"  # empty list

/opt/anaconda/2.3.0/lib/python2.7/abc.pyc in __instancecheck__(cls, instance)
    130         # Inline the cache checking when it's simple.
    131         subclass = getattr(instance, '__class__', None)
--> 132         if subclass is not None and subclass in cls._abc_cache:
    133             return True
    134         subtype = type(instance)

/opt/anaconda/2.3.0/lib/python2.7/_weakrefset.pyc in __contains__(self, item)
     70     def __contains__(self, item):
     71         try:
---> 72             wr = ref(item)
     73         except TypeError:
     74             return False

RuntimeError: maximum recursion depth exceeded

**Comment by tgsmith61591** [comment]
Can you provide services snippets of the code you're running? Also a
snapshot of the head of the H2OFrame might be useful

On Jan 28, 2017 6:54 PM, "mbokshi1" <notifications@github.com> wrote:

Getting a runtime error while trying to return the H2O frame after
H2OOversamplingClassBalancer.

Python 2.7.11 :: Anaconda 2.3.0 (64-bit)
H2O version: 3.10.0.7

Note - error is too long to include in the message box, so trimming it down
by cutting most of the middle of the error trace.

Error:
------------------------------

RuntimeError Traceback (most recent call last)
/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/core/formatters.pyc
in *call*(self, obj)
688 type_pprinters=self.type_printers,
689 deferred_pprinters=self.deferred_printers)
--> 690 printer.pretty(obj)
691 printer.flush()
692 return stream.getvalue()

/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/lib/pretty.pyc in
pretty(self, obj)
407 if callable(meth):
408 return meth(obj, self, cycle)
--> 409 return _default_pprint(obj, self, cycle)
410 finally:
411 self.end_group()

/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/lib/pretty.pyc in
_default_pprint(obj, p, cycle)
527 if _safe_getattr(klass, '*repr*', None) not in
*baseclass_reprs: 528 # A user-provided repr. Find newlines and replace
them with p.break*()
--> 529 _repr_pprint(obj, p, cycle)
530 return
531 p.begin_group(1, '<')

/opt/anaconda/2.3.0/lib/python2.7/site-packages/IPython/lib/pretty.pyc in

*repr_pprint(obj, p, cycle) 709 """A pprint that just redirects to the
normal repr function.""" 710 # Find newlines and replace them with p.break*
()
--> 711 output = repr(obj)
712 for idx,output_line in enumerate(output.splitlines()):
713 if idx:

/home/eobg/.local/lib/python2.7/site-packages/h2o/frame.pyc in *repr*(self)
318 stk = traceback.extract_stack()
319 if not ("IPython" in stk[-2][0] and "info" == stk[-2][2]):
--> 320 self.show()
321 return ""
322

/home/eobg/.local/lib/python2.7/site-packages/h2o/frame.pyc in show(self,
use_pandas)
330 print("This H2OFrame has been removed.")
331 return
--> 332 if not self._ex._cache.is_valid(): self._frame()._ex._cache.fill()
333 if H2ODisplay._in_ipy():
334 import IPython.display

/home/eobg/.local/lib/python2.7/site-packages/h2o/frame.pyc in _frame(self,
fill_cache)
375
376 def _frame(self, fill_cache=False):
--> 377 self._ex._eager_frame()
378 if fill_cache:
379 self._ex._cache.fill()

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in
_eager_frame(self)
83 if not self._cache.is_empty(): return self
84 if self._cache._id is not None: return self # Data already computed
under ID, but not cached locally
---> 85 return self._eval_driver(True)
86
87 def _eager_scalar(self): # returns a scalar (or a list of scalars)

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in
_eval_driver(self, top)
96
97 def _eval_driver(self, top):
---> 98 exec_str = self._do_it(top)
99 res = ExprNode.rapids(exec_str)
100 if 'scalar' in res:

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _do_it(self,
top)
123 if self._cache._id is not None: return self._cache._id # Data already
computed under ID, but not cached
124 # assert isinstance(self._children,tuple)
--> 125 exec_str = "({} {})".format(self._op, "
".join([ExprNode._arg_to_expr(ast) for ast in self._children]))
126 gc_ref_cnt = len(gc.get_referrers(self))
127 if top or gc_ref_cnt >= ExprNode.MAGIC_REF_COUNT:

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in
_arg_to_expr(arg)
136 return "[]" # empty list
137 elif isinstance(arg, ExprNode):
--> 138 return arg._do_it(False)
139 elif isinstance(arg, ASTId):
140 return str(arg)

............................................................
...................................................................

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in _do_it(self,
top)
123 if self._cache._id is not None: return self._cache._id # Data already
computed under ID, but not cached
124 # assert isinstance(self._children,tuple)
--> 125 exec_str = "({} {})".format(self._op, "
".join([ExprNode._arg_to_expr(ast) for ast in self._children]))
126 gc_ref_cnt = len(gc.get_referrers(self))
127 if top or gc_ref_cnt >= ExprNode.MAGIC_REF_COUNT:

/home/eobg/.local/lib/python2.7/site-packages/h2o/expr.pyc in
_arg_to_expr(arg)
132 @staticmethod <https://github.com/staticmethod>
133 def _arg_to_expr(arg):
--> 134 if arg is not None and isinstance(arg, range): arg = list(arg)
135 if arg is None:
136 return "[]" # empty list

/opt/anaconda/2.3.0/lib/python2.7/abc.pyc in *instancecheck*(cls, instance)
130 # Inline the cache checking when it's simple.
131 subclass = getattr(instance, '*class*', None)
--> 132 if subclass is not None and subclass in cls._abc_cache:
133 return True
134 subtype = type(instance)

/opt/anaconda/2.3.0/lib/python2.7/_weakrefset.pyc in *contains*(self, item)
70 def *contains*(self, item):
71 try:
---> 72 wr = ref(item)
73 except TypeError:
74 return False

RuntimeError: maximum recursion depth exceeded

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgsmith61591/skutil/issues/38>, or mute the thread

**Comment by tgsmith61591** [comment]
*several...

**Comment by tgsmith61591** [comment]
This was solved in the latest release, v0.1.6
